# **Coordinate to impulse space Neural Network** 

In this notebbok I will attempt to create Neural Network that learns transformation from coordinate to impulse space. 

Theoretically it should work well for particles that were born in origin.

Here is the main notebook where I train the network.

In [1]:
# Imports

import os

import numpy as np
import pandas as pd

from trackml.dataset import load_event
from trackml.randomize import shuffle_hits
from trackml.score import score_event

# Import keras

from keras.optimizers import Adam
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, BatchNormalization, Lambda
from keras.initializers import TruncatedNormal

Using TensorFlow backend.


In [2]:
# Load data

data_path = '../Data/generated_data/'
x_train_df = pd.read_csv(os.path.join(data_path, "Coordinates_to_impulse_X.csv"))
y_train_df = pd.read_csv(os.path.join(data_path, "Coordinates_to_impulse_Y.csv"))
x_train = np.transpose(np.asarray([x_train_df["0"], x_train_df["1"], x_train_df["2"]]))
y_train = np.transpose(np.asarray([y_train_df["0"], y_train_df["1"], y_train_df["2"]]))

In [3]:
max_coordinates = np.amax(x_train, axis=0)
print(max_coordinates)

[1024.59997559 1024.72998047 2955.5       ]


Model
---

In [105]:
# Define model
def model_architecture():
    model = Sequential()
    
    initializer = TruncatedNormal(stddev=0.1)
    
    # Normalization layer
    model.add(Lambda(lambda x: x / 1000))
    
    model.add(Dense(10, activation='relu'))
    
    model.add(Dense(100, activation='relu'))
    
    model.add(Dense(100, activation='relu'))
    
    model.add(Dense(10, activation='relu'))
    
    model.add(Dense(1))
    
    return model

In [106]:
def train_model(X, Y, learning_rate = 0.001, batch_size=1000, epochs=100):
    # Init model
    model = model_architecture()
    
    # Compiling the model
    optimizer = Adam(lr=learning_rate)
    model.compile(loss='mse', optimizer=optimizer, metrics=['mae'])
    
    # Running and evaluating the model
    history = model.fit(X, Y,
                        batch_size=batch_size,
                        epochs=epochs,
                        verbose=2)
    
    return model

In [107]:
#train model for px
model_px = train_model(x_train, y_train[:,0], epochs=100)

Epoch 1/1000
 - 1s - loss: 0.5036 - mean_absolute_error: 0.3485
Epoch 2/1000
 - 0s - loss: 0.4350 - mean_absolute_error: 0.3015
Epoch 3/1000
 - 0s - loss: 0.4099 - mean_absolute_error: 0.2839
Epoch 4/1000
 - 0s - loss: 0.3965 - mean_absolute_error: 0.2828
Epoch 5/1000
 - 0s - loss: 0.3851 - mean_absolute_error: 0.2755
Epoch 6/1000
 - 0s - loss: 0.3805 - mean_absolute_error: 0.2746
Epoch 7/1000
 - 0s - loss: 0.3782 - mean_absolute_error: 0.2739
Epoch 8/1000
 - 0s - loss: 0.3751 - mean_absolute_error: 0.2739
Epoch 9/1000
 - 0s - loss: 0.3735 - mean_absolute_error: 0.2737
Epoch 10/1000
 - 0s - loss: 0.3717 - mean_absolute_error: 0.2717
Epoch 11/1000
 - 0s - loss: 0.3711 - mean_absolute_error: 0.2708
Epoch 12/1000
 - 0s - loss: 0.3690 - mean_absolute_error: 0.2700
Epoch 13/1000
 - 0s - loss: 0.3674 - mean_absolute_error: 0.2702
Epoch 14/1000
 - 0s - loss: 0.3667 - mean_absolute_error: 0.2698
Epoch 15/1000
 - 0s - loss: 0.3659 - mean_absolute_error: 0.2690
Epoch 16/1000
 - 0s - loss: 0.3649

Epoch 127/1000
 - 0s - loss: 0.2760 - mean_absolute_error: 0.2602
Epoch 128/1000
 - 0s - loss: 0.2694 - mean_absolute_error: 0.2618
Epoch 129/1000
 - 0s - loss: 0.2737 - mean_absolute_error: 0.2607
Epoch 130/1000
 - 0s - loss: 0.2717 - mean_absolute_error: 0.2582
Epoch 131/1000
 - 0s - loss: 0.2728 - mean_absolute_error: 0.2603
Epoch 132/1000
 - 0s - loss: 0.2657 - mean_absolute_error: 0.2574
Epoch 133/1000
 - 0s - loss: 0.2742 - mean_absolute_error: 0.2611
Epoch 134/1000
 - 0s - loss: 0.2690 - mean_absolute_error: 0.2607
Epoch 135/1000
 - 0s - loss: 0.2722 - mean_absolute_error: 0.2583
Epoch 136/1000
 - 0s - loss: 0.2872 - mean_absolute_error: 0.2688
Epoch 137/1000
 - 0s - loss: 0.2722 - mean_absolute_error: 0.2582
Epoch 138/1000
 - 0s - loss: 0.2707 - mean_absolute_error: 0.2593
Epoch 139/1000
 - 0s - loss: 0.2737 - mean_absolute_error: 0.2593
Epoch 140/1000
 - 0s - loss: 0.2646 - mean_absolute_error: 0.2596
Epoch 141/1000
 - 0s - loss: 0.2725 - mean_absolute_error: 0.2605
Epoch 142/

 - 0s - loss: 0.2417 - mean_absolute_error: 0.2511
Epoch 252/1000
 - 0s - loss: 0.2412 - mean_absolute_error: 0.2506
Epoch 253/1000
 - 0s - loss: 0.2507 - mean_absolute_error: 0.2535
Epoch 254/1000
 - 0s - loss: 0.2459 - mean_absolute_error: 0.2545
Epoch 255/1000
 - 0s - loss: 0.2371 - mean_absolute_error: 0.2509
Epoch 256/1000
 - 0s - loss: 0.2414 - mean_absolute_error: 0.2526
Epoch 257/1000
 - 0s - loss: 0.2430 - mean_absolute_error: 0.2515
Epoch 258/1000
 - 0s - loss: 0.2495 - mean_absolute_error: 0.2560
Epoch 259/1000
 - 0s - loss: 0.2424 - mean_absolute_error: 0.2547
Epoch 260/1000
 - 0s - loss: 0.2332 - mean_absolute_error: 0.2515
Epoch 261/1000
 - 0s - loss: 0.2393 - mean_absolute_error: 0.2514
Epoch 262/1000
 - 0s - loss: 0.2480 - mean_absolute_error: 0.2541
Epoch 263/1000
 - 0s - loss: 0.2382 - mean_absolute_error: 0.2514
Epoch 264/1000
 - 0s - loss: 0.2433 - mean_absolute_error: 0.2518
Epoch 265/1000
 - 0s - loss: 0.3607 - mean_absolute_error: 0.2660
Epoch 266/1000
 - 0s - lo

Epoch 376/1000
 - 0s - loss: 0.2295 - mean_absolute_error: 0.2480
Epoch 377/1000
 - 0s - loss: 0.2434 - mean_absolute_error: 0.2495
Epoch 378/1000
 - 0s - loss: 0.2352 - mean_absolute_error: 0.2517
Epoch 379/1000
 - 0s - loss: 0.2281 - mean_absolute_error: 0.2477
Epoch 380/1000
 - 0s - loss: 0.2261 - mean_absolute_error: 0.2458
Epoch 381/1000
 - 0s - loss: 0.2239 - mean_absolute_error: 0.2480
Epoch 382/1000
 - 0s - loss: 0.2409 - mean_absolute_error: 0.2557
Epoch 383/1000
 - 0s - loss: 0.2314 - mean_absolute_error: 0.2527
Epoch 384/1000
 - 0s - loss: 0.2490 - mean_absolute_error: 0.2494
Epoch 385/1000
 - 0s - loss: 0.2355 - mean_absolute_error: 0.2509
Epoch 386/1000
 - 0s - loss: 0.2436 - mean_absolute_error: 0.2489
Epoch 387/1000
 - 0s - loss: 0.2355 - mean_absolute_error: 0.2509
Epoch 388/1000
 - 0s - loss: 0.2304 - mean_absolute_error: 0.2475
Epoch 389/1000
 - 0s - loss: 0.2239 - mean_absolute_error: 0.2487
Epoch 390/1000
 - 0s - loss: 0.2222 - mean_absolute_error: 0.2458
Epoch 391/

 - 0s - loss: 0.2485 - mean_absolute_error: 0.2511
Epoch 501/1000
 - 0s - loss: 0.2367 - mean_absolute_error: 0.2490
Epoch 502/1000
 - 0s - loss: 0.2300 - mean_absolute_error: 0.2479
Epoch 503/1000
 - 0s - loss: 0.2308 - mean_absolute_error: 0.2491
Epoch 504/1000
 - 0s - loss: 0.2221 - mean_absolute_error: 0.2474
Epoch 505/1000
 - 0s - loss: 0.2174 - mean_absolute_error: 0.2439
Epoch 506/1000
 - 0s - loss: 0.2142 - mean_absolute_error: 0.2459
Epoch 507/1000
 - 0s - loss: 0.2155 - mean_absolute_error: 0.2448
Epoch 508/1000
 - 0s - loss: 0.2247 - mean_absolute_error: 0.2468
Epoch 509/1000
 - 0s - loss: 0.3281 - mean_absolute_error: 0.2538
Epoch 510/1000
 - 0s - loss: 0.3092 - mean_absolute_error: 0.2548
Epoch 511/1000
 - 0s - loss: 0.2977 - mean_absolute_error: 0.2535
Epoch 512/1000
 - 0s - loss: 0.2886 - mean_absolute_error: 0.2524
Epoch 513/1000
 - 0s - loss: 0.2686 - mean_absolute_error: 0.2537
Epoch 514/1000
 - 0s - loss: 0.2508 - mean_absolute_error: 0.2527
Epoch 515/1000
 - 0s - lo

Epoch 625/1000
 - 0s - loss: 0.2250 - mean_absolute_error: 0.2486
Epoch 626/1000
 - 0s - loss: 0.2193 - mean_absolute_error: 0.2447
Epoch 627/1000
 - 0s - loss: 0.2223 - mean_absolute_error: 0.2474
Epoch 628/1000
 - 0s - loss: 0.2134 - mean_absolute_error: 0.2455
Epoch 629/1000
 - 0s - loss: 0.2086 - mean_absolute_error: 0.2424
Epoch 630/1000
 - 0s - loss: 0.2473 - mean_absolute_error: 0.2493
Epoch 631/1000
 - 0s - loss: 0.2364 - mean_absolute_error: 0.2489
Epoch 632/1000
 - 0s - loss: 0.2250 - mean_absolute_error: 0.2488
Epoch 633/1000
 - 0s - loss: 0.2122 - mean_absolute_error: 0.2440
Epoch 634/1000
 - 0s - loss: 0.2191 - mean_absolute_error: 0.2428
Epoch 635/1000
 - 0s - loss: 0.2254 - mean_absolute_error: 0.2466
Epoch 636/1000
 - 0s - loss: 0.2213 - mean_absolute_error: 0.2452
Epoch 637/1000
 - 0s - loss: 0.2380 - mean_absolute_error: 0.2480
Epoch 638/1000
 - 0s - loss: 0.2140 - mean_absolute_error: 0.2452
Epoch 639/1000
 - 0s - loss: 0.2120 - mean_absolute_error: 0.2421
Epoch 640/

Epoch 750/1000
 - 0s - loss: 0.2121 - mean_absolute_error: 0.2445
Epoch 751/1000
 - 0s - loss: 0.2114 - mean_absolute_error: 0.2414
Epoch 752/1000
 - 0s - loss: 0.2007 - mean_absolute_error: 0.2384
Epoch 753/1000
 - 0s - loss: 0.2075 - mean_absolute_error: 0.2409
Epoch 754/1000
 - 0s - loss: 0.2517 - mean_absolute_error: 0.2455
Epoch 755/1000
 - 0s - loss: 0.2221 - mean_absolute_error: 0.2440
Epoch 756/1000
 - 0s - loss: 0.2066 - mean_absolute_error: 0.2409
Epoch 757/1000
 - 0s - loss: 0.1981 - mean_absolute_error: 0.2399
Epoch 758/1000
 - 0s - loss: 0.2171 - mean_absolute_error: 0.2423
Epoch 759/1000
 - 0s - loss: 0.2034 - mean_absolute_error: 0.2405
Epoch 760/1000
 - 0s - loss: 0.2151 - mean_absolute_error: 0.2435
Epoch 761/1000
 - 0s - loss: 0.2178 - mean_absolute_error: 0.2418
Epoch 762/1000
 - 0s - loss: 0.2079 - mean_absolute_error: 0.2384
Epoch 763/1000
 - 0s - loss: 0.1977 - mean_absolute_error: 0.2374
Epoch 764/1000
 - 0s - loss: 0.1927 - mean_absolute_error: 0.2356
Epoch 765/

 - 0s - loss: 0.2005 - mean_absolute_error: 0.2411
Epoch 875/1000
 - 0s - loss: 0.2066 - mean_absolute_error: 0.2408
Epoch 876/1000
 - 0s - loss: 0.2021 - mean_absolute_error: 0.2392
Epoch 877/1000
 - 0s - loss: 0.2049 - mean_absolute_error: 0.2389
Epoch 878/1000
 - 0s - loss: 0.2006 - mean_absolute_error: 0.2376
Epoch 879/1000
 - 0s - loss: 0.2493 - mean_absolute_error: 0.2476
Epoch 880/1000
 - 0s - loss: 0.2157 - mean_absolute_error: 0.2413
Epoch 881/1000
 - 0s - loss: 0.2060 - mean_absolute_error: 0.2397
Epoch 882/1000
 - 0s - loss: 0.2161 - mean_absolute_error: 0.2414
Epoch 883/1000
 - 0s - loss: 0.2798 - mean_absolute_error: 0.2549
Epoch 884/1000
 - 0s - loss: 0.2375 - mean_absolute_error: 0.2440
Epoch 885/1000
 - 0s - loss: 0.2138 - mean_absolute_error: 0.2403
Epoch 886/1000
 - 0s - loss: 0.2018 - mean_absolute_error: 0.2385
Epoch 887/1000
 - 0s - loss: 0.2095 - mean_absolute_error: 0.2395
Epoch 888/1000
 - 0s - loss: 0.1959 - mean_absolute_error: 0.2394
Epoch 889/1000
 - 0s - lo

Epoch 999/1000
 - 0s - loss: 0.2996 - mean_absolute_error: 0.2459
Epoch 1000/1000
 - 0s - loss: 0.2983 - mean_absolute_error: 0.2453


In [63]:
#train model for px
model_py = train_model(x_train, y_train[:,1])

Epoch 1/100
 - 1s - loss: 0.4084 - mean_absolute_error: 0.3521
Epoch 2/100
 - 0s - loss: 0.3779 - mean_absolute_error: 0.3309
Epoch 3/100
 - 0s - loss: 0.3777 - mean_absolute_error: 0.3305
Epoch 4/100
 - 0s - loss: 0.3762 - mean_absolute_error: 0.3293
Epoch 5/100
 - 0s - loss: 0.3736 - mean_absolute_error: 0.3276
Epoch 6/100
 - 0s - loss: 0.3694 - mean_absolute_error: 0.3254
Epoch 7/100
 - 0s - loss: 0.3598 - mean_absolute_error: 0.3175
Epoch 8/100
 - 0s - loss: 0.3486 - mean_absolute_error: 0.3095
Epoch 9/100
 - 0s - loss: 0.3367 - mean_absolute_error: 0.3023
Epoch 10/100
 - 0s - loss: 0.3273 - mean_absolute_error: 0.2973
Epoch 11/100
 - 0s - loss: 0.3203 - mean_absolute_error: 0.2937
Epoch 12/100
 - 0s - loss: 0.3157 - mean_absolute_error: 0.2920
Epoch 13/100
 - 0s - loss: 0.3121 - mean_absolute_error: 0.2901
Epoch 14/100
 - 0s - loss: 0.3088 - mean_absolute_error: 0.2893
Epoch 15/100
 - 0s - loss: 0.3055 - mean_absolute_error: 0.2863
Epoch 16/100
 - 0s - loss: 0.3022 - mean_absolute

In [64]:
#train model for px
model_pz = train_model(x_train, y_train[:,2])

Epoch 1/100
 - 1s - loss: 62.0025 - mean_absolute_error: 3.7757
Epoch 2/100
 - 0s - loss: 52.3037 - mean_absolute_error: 3.1779
Epoch 3/100
 - 0s - loss: 47.8323 - mean_absolute_error: 3.0796
Epoch 4/100
 - 0s - loss: 45.8115 - mean_absolute_error: 3.1257
Epoch 5/100
 - 0s - loss: 44.8183 - mean_absolute_error: 3.2009
Epoch 6/100
 - 0s - loss: 44.2177 - mean_absolute_error: 3.2550
Epoch 7/100
 - 0s - loss: 43.7131 - mean_absolute_error: 3.2740
Epoch 8/100
 - 0s - loss: 43.1315 - mean_absolute_error: 3.2436
Epoch 9/100
 - 0s - loss: 42.4238 - mean_absolute_error: 3.1609
Epoch 10/100
 - 0s - loss: 41.6316 - mean_absolute_error: 3.0610
Epoch 11/100
 - 0s - loss: 40.8195 - mean_absolute_error: 2.9583
Epoch 12/100
 - 0s - loss: 40.0928 - mean_absolute_error: 2.9002
Epoch 13/100
 - 0s - loss: 39.4104 - mean_absolute_error: 2.8496
Epoch 14/100
 - 0s - loss: 38.7911 - mean_absolute_error: 2.8206
Epoch 15/100
 - 0s - loss: 38.2006 - mean_absolute_error: 2.7957
Epoch 16/100
 - 0s - loss: 37.6446

In [108]:
lim = 10
np.set_printoptions(precision=3, suppress = True)
predict_px = model_px.predict(x_train[0:lim], batch_size=lim)
predict_py = model_py.predict(x_train[0:lim], batch_size=lim)
predict_pz = model_pz.predict(x_train[0:lim], batch_size=lim)
predict = np.concatenate((predict_px, predict_py, predict_pz), axis=1)
print(predict[0:lim])
print(y_train[0:lim])
#print(x_train[0:lim])

[[-0.283 -0.61  -1.596]
 [-0.388  0.32  -2.608]
 [-0.459  0.2   -0.004]
 [-0.527 -0.37  11.008]
 [-0.712  0.234  0.255]
 [-0.52  -0.527  0.618]
 [-0.273  0.418  1.523]
 [ 0.573  0.938 -2.593]
 [-0.116  0.729 -0.312]
 [-0.385 -0.252  2.805]]
[[-0.226 -0.172 -0.411]
 [-0.144  0.177 -0.429]
 [-0.44   0.167 -0.745]
 [-0.189 -0.128  3.971]
 [-0.399  0.292 -0.63 ]
 [-0.773 -0.915  1.504]
 [-0.499  0.495  1.464]
 [ 1.13   0.931 -4.862]
 [-0.353  1.222  1.02 ]
 [-0.179 -0.061  0.797]]


Try clustering
---

In [115]:
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import DBSCAN

def predict(X, eps=0.01):
    cl = DBSCAN(eps, min_samples=1, algorithm='kd_tree')
    labels = cl.fit_predict(StandardScaler().fit_transform(X))
    return labels

#score
def create_one_event_submission(event_id, hits, labels):
    sub_data = np.column_stack(([event_id]*len(hits), hits.hit_id.values, labels))
    submission = pd.DataFrame(data=sub_data, columns=["event_id", "hit_id", "track_id"]).astype(int)
    return submission

def try_clustering(hits, X):
    labels = predict(X)
    submission = create_one_event_submission(0, hits, labels)
    score = score_event(truth, submission)
    print("Your score: ", score)

In [116]:
data_path = '../Data/train_100_events/'
event_prefix = 'event000001000'
hits, cells, particles, truth = load_event(os.path.join(data_path, event_prefix))

X = np.transpose([hits.x.values, hits.y.values, hits.z.values])

y_predict = model.predict(X, batch_size=10000)

try_clustering(hits, y_predict)

Your score:  0.0
